name: Publish Releases to WinGet
on:
  release:
    types: [published]
jobs:
  publish-alpha:
    runs-on: ubuntu-latest
    if: contains(github.event.release.tag_name, '-alpha')
    steps:
      - uses: vedantmgoyal9/winget-releaser@3e78d7ff0f525445bca5d6a989d31cdca383372e
        with:
          identifier: prayag17.Blink.Alpha
          version: ${{ github.event.release.tag_name }}
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}

  publish-stable:
    runs-on: ubuntu-latest
    if: "!contains(github.event.release.tag_name, '-alpha')"
    steps:
      - uses: vedantmgoyal9/winget-releaser@3e78d7ff0f525445bca5d6a989d31cdca383372e
        with:
          identifier: prayag17.Blink
          version: ${{ github.event.release.tag_name }}
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
